/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cirugia;

import Models.ModelPractica;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONArray;
import org.json.JSONException;

/**
 *
 * @author djaime
 */
public class DialogoImagenPractica extends javax.swing.JDialog {

    /**
     * Creates new form DialogoImagenPractica
     */
    java.awt.Frame parent;
    public ControladorCirugia controlador;
            
    public DialogoImagenPractica(java.awt.Frame parent, boolean modal, ControladorCirugia controlador) {
        super(parent, modal);
        this.controlador = controlador;
        this.parent = parent;
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPracticas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaPracticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaPracticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPracticasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPracticas);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton2.setText("Buscar Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tablaPracticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPracticasMouseClicked
        if(evt.getClickCount() >= 2){
            DialogoPorcentajePractica dialogo = new DialogoPorcentajePractica(parent, true, this, tablaPracticas.getSelectedRow());
            dialogo.setVisible(true);
//            int mensaje = JOptionPane.showConfirmDialog(null,"¿Desea quitar la practica?", "Mensaje de confirmación", JOptionPane.YES_NO_OPTION);
//            if(mensaje == JOptionPane.YES_OPTION){
//                try {
//                    controlador.quitarPractica(tablaPracticas.getSelectedRow());
//                    cargarTabla();
//                } catch (JSONException ex) {}
//            }
        }
    }//GEN-LAST:event_tablaPracticasMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DialogoBuscarPractica dialogo = new DialogoBuscarPractica(parent, true, controlador, this);
        dialogo.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void cargarTabla(){
        try {
            tablaPracticas.setModel(new ModelPractica(new JSONArray(controlador.cirugia.practicajson)));
            tablaPracticas.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablaPracticas.getColumnModel().getColumn(1).setPreferredWidth(220);
            tablaPracticas.getColumnModel().getColumn(2).setPreferredWidth(20);
            tablaPracticas.getColumnModel().getColumn(3).setPreferredWidth(20);
            tablaPracticas.getColumnModel().getColumn(4).setPreferredWidth(20);
        } catch (JSONException ex) {
            Logger.getLogger(DialogoImagenPractica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPracticas;
    // End of variables declaration//GEN-END:variables
}
