/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cirugia;

import Models.ModelAyudante;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONArray;
import org.json.JSONException;

/**
 *
 * @author djaime
 */
public class DialogoAsociarAyudante extends javax.swing.JDialog {

    JSONArray array = null;
    
    /**
     * Creates new form DialogoAsociarAyudante
     */
    ControladorCirugia controlador;
    DialogoPorcentajePractica dialogo;
    
    public DialogoAsociarAyudante(java.awt.Frame parent, boolean modal, DialogoPorcentajePractica dialogo, ControladorCirugia controlador) {
        super(parent, modal);
        initComponents();
        this.dialogo = dialogo;
        this.controlador = controlador;
        cargarTabla();
    }

    public void cargarTabla(){
        try {
            array = new JSONArray(controlador.cirugia.ayudantejson);
            tablaAyudante.setModel(new ModelAyudante(array));
        } catch (JSONException ex) {
            Logger.getLogger(DialogoAsociarAyudante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAyudante = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaAyudante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaAyudante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAyudanteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAyudante);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jButton1.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tablaAyudanteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAyudanteMouseClicked
        if(evt.getClickCount() >= 2){
            try {
                dialogo.agregarMedico(array.getJSONObject(tablaAyudante.getSelectedRow()));
                this.dispose();
                //System.out.println(array.getJSONObject(tablaAyudante.getSelectedRow()).toString());
            } catch (JSONException ex) {
                Logger.getLogger(DialogoAsociarAyudante.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tablaAyudanteMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAyudante;
    // End of variables declaration//GEN-END:variables
}
